// Scouting assignments, generated by an admin from the Team tab and stored
// at teams/{teamId}/config/pitAssignments and .../matchAssignments. Pure
// generation logic lives here so it's testable with a seeded rng.

import type { EventMatch } from "@/lib/eventData";
import { isPlayed } from "@/lib/pitDashboard";

export interface PitAssignmentsDoc {
  /** uid → team numbers that scout pit-scouts. */
  byScout: Record<string, number[]>;
  /** uid → display name, snapshotted at generation time. */
  scoutNames: Record<string, string>;
  /** Team numbers crossed off by their scout. Missing on older docs. */
  completedTeams?: number[];
  generatedAt: number;
}

export interface MatchSlot {
  matchKey: string;
  compLevel: string;
  matchNumber: number;
  teamNumber: number;
  alliance: "red" | "blue";
  uid: string;
}

export interface MatchAssignmentsDoc {
  slots: MatchSlot[];
  scoutNames: Record<string, string>;
  /** slotKey() values crossed off by their scout. Missing on older docs. */
  completedSlots?: string[];
  generatedAt: number;
}

/** Stable id for a match slot, used for the crossed-off list. */
export function slotKey(
  slot: Pick<MatchSlot, "matchKey" | "teamNumber">,
): string {
  return `${slot.matchKey}:${slot.teamNumber}`;
}

/**
 * The scout's slots in the next `lookahead` unplayed matches, tagged with
 * how far out the match is (0 = on the field now, 1 = up next). Drives the
 * "your scouting match is up" banner.
 */
export function upcomingSlots(
  slots: readonly MatchSlot[],
  matches: readonly EventMatch[],
  uid: string,
  lookahead: number = 2,
): Array<{ slot: MatchSlot; position: number }> {
  const upcoming = matches.filter((m) => !isPlayed(m)).slice(0, lookahead);
  const positionByKey = new Map(upcoming.map((m, i) => [m.key, i]));
  return slots
    .filter((s) => s.uid === uid && positionByKey.has(s.matchKey))
    .map((slot) => ({ slot, position: positionByKey.get(slot.matchKey)! }))
    .sort((a, b) => a.position - b.position);
}

export function shuffle<T>(
  list: readonly T[],
  rng: () => number = Math.random,
): T[] {
  const next = [...list];
  for (let i = next.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [next[i], next[j]] = [next[j], next[i]];
  }
  return next;
}

/**
 * Randomly deal every event team to a scout, keeping counts even (each scout
 * gets floor or ceil of teams/scouts). Every scout appears in the result,
 * even with an empty list, so the Assignments tab can show "no teams".
 */
export function assignPitScouts(
  teamNumbers: readonly number[],
  scoutUids: readonly string[],
  rng: () => number = Math.random,
): Record<string, number[]> {
  const byScout: Record<string, number[]> = {};
  if (scoutUids.length === 0) return byScout;

  const scouts = shuffle(scoutUids, rng);
  for (const uid of scouts) byScout[uid] = [];

  const teams = shuffle(teamNumbers, rng);
  teams.forEach((team, i) => {
    byScout[scouts[i % scouts.length]].push(team);
  });
  for (const uid of scouts) byScout[uid].sort((a, b) => a - b);
  return byScout;
}

/**
 * Cover every team in every match: walk the matches in order and hand each
 * of the 6 alliance slots to the next scout in a shuffled rotation. With 6+
 * scouts each match gets 6 different scouts; with fewer, scouts double up
 * within a match so no team goes unscouted. The rotation carries across
 * matches, keeping total load even.
 */
export function assignMatchScouts(
  matches: readonly EventMatch[],
  scoutUids: readonly string[],
  rng: () => number = Math.random,
): MatchSlot[] {
  if (scoutUids.length === 0) return [];
  const rotation = shuffle(scoutUids, rng);
  let cursor = 0;

  const slots: MatchSlot[] = [];
  for (const match of matches) {
    const sides: Array<{ alliance: "red" | "blue"; teams: number[] }> = [
      { alliance: "red", teams: match.red },
      { alliance: "blue", teams: match.blue },
    ];
    for (const side of sides) {
      for (const teamNumber of side.teams) {
        slots.push({
          matchKey: match.key,
          compLevel: match.compLevel,
          matchNumber: match.matchNumber,
          teamNumber,
          alliance: side.alliance,
          uid: rotation[cursor % rotation.length],
        });
        cursor++;
      }
    }
  }
  return slots;
}
