// Scouting assignments, generated by an admin from the Team tab and stored
// at teams/{teamId}/config/pitAssignments and .../matchAssignments. Pure
// generation logic lives here so it's testable with a seeded rng.

import type { EventMatch } from "@/lib/eventData";
import { isPlayed } from "@/lib/pitDashboard";
import { clampMatchesPerScout } from "@/lib/scoutDuty";

export interface PitAssignmentsDoc {
  /** uid → team numbers that scout pit-scouts. */
  byScout: Record<string, number[]>;
  /** uid → display name, snapshotted at generation time. */
  scoutNames: Record<string, string>;
  /** Team numbers crossed off by their scout. Missing on older docs. */
  completedTeams?: number[];
  generatedAt: number;
}

export interface MatchSlot {
  matchKey: string;
  compLevel: string;
  matchNumber: number;
  teamNumber: number;
  alliance: "red" | "blue";
  uid: string;
}

export interface MatchAssignmentsDoc {
  slots: MatchSlot[];
  scoutNames: Record<string, string>;
  /** slotKey() values crossed off by their scout. Missing on older docs. */
  completedSlots?: string[];
  generatedAt: number;
}

/** Stable id for a match slot, used for the crossed-off list. */
export function slotKey(
  slot: Pick<MatchSlot, "matchKey" | "teamNumber">,
): string {
  return `${slot.matchKey}:${slot.teamNumber}`;
}

/**
 * Stable partition that sinks crossed-off entries to the end of the list, so
 * a scout's remaining work always sits at the top. Relative order inside each
 * group is preserved (teams stay numerically sorted, slots stay in match
 * order).
 */
export function completedLast<T>(
  items: readonly T[],
  isDone: (item: T) => boolean,
): T[] {
  return [...items.filter((item) => !isDone(item)), ...items.filter(isDone)];
}

/**
 * The scout's slots in the next `lookahead` unplayed matches, tagged with
 * how far out the match is (0 = on the field now, 1 = up next). Drives the
 * "your scouting match is up" banner.
 */
export function upcomingSlots(
  slots: readonly MatchSlot[],
  matches: readonly EventMatch[],
  uid: string,
  lookahead: number = 2,
): Array<{ slot: MatchSlot; position: number }> {
  const upcoming = matches.filter((m) => !isPlayed(m)).slice(0, lookahead);
  const positionByKey = new Map(upcoming.map((m, i) => [m.key, i]));
  return slots
    .filter((s) => s.uid === uid && positionByKey.has(s.matchKey))
    .map((slot) => ({ slot, position: positionByKey.get(slot.matchKey)! }))
    .sort((a, b) => a.position - b.position);
}

export function shuffle<T>(
  list: readonly T[],
  rng: () => number = Math.random,
): T[] {
  const next = [...list];
  for (let i = next.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [next[i], next[j]] = [next[j], next[i]];
  }
  return next;
}

/**
 * Randomly deal every event team to a scout, keeping counts even (each scout
 * gets floor or ceil of teams/scouts). Every scout appears in the result,
 * even with an empty list, so the Assignments tab can show "no teams".
 */
export function assignPitScouts(
  teamNumbers: readonly number[],
  scoutUids: readonly string[],
  rng: () => number = Math.random,
): Record<string, number[]> {
  const byScout: Record<string, number[]> = {};
  if (scoutUids.length === 0) return byScout;

  const scouts = shuffle(scoutUids, rng);
  for (const uid of scouts) byScout[uid] = [];

  const teams = shuffle(teamNumbers, rng);
  teams.forEach((team, i) => {
    byScout[scouts[i % scouts.length]].push(team);
  });
  for (const uid of scouts) byScout[uid].sort((a, b) => a - b);
  return byScout;
}

/**
 * Cover every team in every match by station. A station is a seat in the
 * schedule — Red 1, Red 2, … Blue 3 — and one scout holds a single station for
 * `matchesPerScout` consecutive matches before rotating off and handing it to
 * the next scout in a shuffled rotation.
 *
 * Holding a station (rather than being dealt loose slots) is what makes a
 * shift worth sitting through: the scout watches the same seat match after
 * match instead of hopping between robots, and comes off duty on a predictable
 * boundary. The rotation cursor runs across every block, so with more scouts
 * than stations everyone takes turns and the total load stays even.
 *
 * With fewer than 6 scouts eligible, the rotation wraps inside a block and a
 * scout holds more than one station at once — the same doubling-up the flat
 * rotation used to do, and still better than leaving a robot unscouted.
 */
export function assignMatchScouts(
  matches: readonly EventMatch[],
  scoutUids: readonly string[],
  matchesPerScout: number,
  rng: () => number = Math.random,
): MatchSlot[] {
  if (scoutUids.length === 0) return [];
  const rotation = shuffle(scoutUids, rng);
  const blockSize = clampMatchesPerScout(matchesPerScout);
  let cursor = 0;

  // Who is holding each station for the block currently being laid out.
  let block = -1;
  let byStation: string[] = [];

  const slots: MatchSlot[] = [];
  matches.forEach((match, index) => {
    const thisBlock = Math.floor(index / blockSize);
    if (thisBlock !== block) {
      block = thisBlock;
      byStation = Array.from({ length: STATIONS_PER_MATCH }, () => {
        const uid = rotation[cursor % rotation.length];
        cursor++;
        return uid;
      });
    }

    let station = 0;
    for (const side of allianceSides(match)) {
      for (const teamNumber of side.teams) {
        slots.push({
          ...slotFor(match, teamNumber, side.alliance),
          // A match with an unusual alliance size can run past the six
          // standard stations; wrap rather than hand out an undefined scout.
          uid: byStation[station % byStation.length],
        });
        station++;
      }
    }
  });
  return slots;
}

/** Red 1–3 then Blue 1–3 — the seats one scout each holds through a shift. */
const STATIONS_PER_MATCH = 6;

function allianceSides(
  match: EventMatch,
): Array<{ alliance: "red" | "blue"; teams: number[] }> {
  return [
    { alliance: "red", teams: match.red },
    { alliance: "blue", teams: match.blue },
  ];
}

function slotFor(
  match: EventMatch,
  teamNumber: number,
  alliance: "red" | "blue",
): Omit<MatchSlot, "uid"> {
  return {
    matchKey: match.key,
    compLevel: match.compLevel,
    matchNumber: match.matchNumber,
    teamNumber,
    alliance,
  };
}

